#+title: Stargaze user manual

(very early draft)


* Lexical syntax

** Comment

Comment in Stargaze starts with =;=.

** Booleans

Only the strings =#t= and =#f= are boolean values; they evaluate to true and false respectively.

** Strings

There's only one kind of syntax for string literals: ="{string-piece}*"=, where =string-piece= is one of:

+ Normal characters.
+ Escape sequences, which starts with =\= and is of the following format:
  + =\r=, =\n=, =\b=, =\t=, =\\=, =\"=, =\v=, =\f=, for carriage return, linefeed, backspace, horizontal tab, slash, double quote, vertical tab and form feed respectively.
  + =\xHEX=, where =HEX= is the codepoint of character in hexadecimal, e.g. =\x61= is the same as =a=.

** Characters

Two kinds of syntax for character literals:

+ =#\NAME= where =NAME= is the name for the character. =NAME= is often the character itself (e.g. =#\a= refers to the character =a=), but exceptions exist; see below.
+ =#ch{HEX}= where =HEX= is the codepoint in hexadecimal, e.g. =#ch{61}= is the same as =#\a=.

As for the first kind, Scheme R4RS only explicitly declares a =#\space= and a =#\newline=. Stargaze (partly) follows [[https://groups.csail.mit.edu/mac/ftpdir/scheme-7.4/doc-html/scheme_6.html][the convention in MIT Scheme]], except that =#\newline= always corresponds to the ASCII LF regardless of the operating system. For this reason the following "character name"s are also defined in Stargaze:

+ All of the standard ASCII names for non-printing characters are supported. They can be used by prefixing with =#\=, e.g. =#\NUL=:
  #+begin_src 
  NUL     SOH     STX     ETX     EOT     ENQ     ACK     BEL
  BS      HT      LF      VT      FF      CR      SO      SI
  DLE     DC1     DC2     DC3     DC4     NAK     SYN     ETB
  CAN     EM      SUB     ESC     FS      GS      RS      US
  DEL
  #+end_src
+ A few other names are also defined:
  + =#\esc=, for =#\ESC=. MIT Scheme used the string =#\altmode=, which we 
  + =#\backspace= for =#\BS=
  + =#\linefeed= for =#\LF= (also, as stated above, =#\newline=)
  + =#\tab= for =#\HT=
  + =#\return= for =#\CR=

** Vector

Vector literals can be constructed by surrounding values with =#{= and =}=.

* Built-in primitives

+ =(def NAME BODY)=: Bind the value =BODY= to the name =NAME= in the current environment.
+ =(fn ARGLIST BODY)=: Anonymous function.
+ =(if COND THEN_CLAUSE ELSE_CLAUSE)=: Simple branching.
+ =(cond (COND1 CLAUSE1) ...)=: Multiway branching.
+ =(let ((NAME1 EXP1) ...) BODY ...)=: =let=-binding.
+ =(letrec ((NAME1 EXP1) ...) BODY ...)=: =letrec=-binding.
+ =(quote ...)=: Quote its argument as symbolic values
+ =(set! NAME VALUE)=: Assign =VALUE= to the name =NAME=.
+ =(begin EXP1 ...)=: Executes =EXP1= and the rest in the order they appear in the argument list. Returns the evaluated value of the last argument..

** Module-related

+ =(include STR)=: Include a file.
+ =(import MOD RENAME?)=:
  + =MOD= can be one of two options:
    + A string, which refers to the module.
    + =(STR PREFIX)=, which prefix all exported name in =STR= with =PREFIX=.
      + e.g. assumes that =mymodule= exports =func1=, =func2= and =func3=; =(import ("mymodule" xyz))= would import =func1= as =xyzfunc1=, =func2= as =xyzfunc2=, =func3= as =xyzfunc3=.
  + =RENAME= is one of two followings:
    + Nothing, in which case the form would be =(import MOD)=; this would import *all* exported name in =MOD=.
    + A list of =(NAME NEWNAME)=, which would only import the *exported* names described by =NAME=, which would bind to =NEWNAME= when importing. This renaming takes precedence over prefixes, so =(import ("abc" abc) (myfunc1 defmyfunc1))= would import =myfunc1= from module ="abc"= into =defmyfunc1= instead of =abcmyfunc1= or =abcdefmyfunc1=.
  + Note that =(import MOD)= means import *all* names from =MOD=, while =(import MOD ())= means import all the exported names in =()=, which means none of the exported names.
in the imported module; =NEW_NAME= would be the effective name in the *importing* module for =NAME= in the *imported* module.
+ =(export NAME ...)=: Export 

** Miscellaneous

+ =(atom? EXP)=: Check if =EXP= is an atom, i.e. a symbol, an integer, a boolean, a string, a character, or the empty list.

** Integer

+ =(int? EXP)=: Check if =EXP= is an integer.
+ =(add EXP ...)=: Return the sum of the arguments.
+ =(sub EXP1 ...)=: Return =EXP1 - EXP2 - ...=.
+ =(mul EXP ...)=: Return the product of the arguments.
+ =(div EXP1 ...)=: Return =EXP1 div EXP2 div ...=
+ =(mod EXP1 EXP2)=: Return =EXP1 % EXP2=.
+ =(leq EXP1 EXP2)=, =(lt EXP1 EXP2)=, =(geq EXP1 EXP2)=, =(gt EXP1 EXP2)=: Check if =EXP1= is smaller or equal than, strictly smaller than, greater or equal than, and strictly greater than =EXP2= respectively.

** Floating-point

+ =(float? EXP)=: Check if =EXP= is an integer.
+ =(addf EXP ...)=: Return the sum of the arguments.
+ =(subf EXP1 ...)=: Return =EXP1 - EXP2 - ...=.
+ =(mulf EXP ...)=: Return the product of the arguments.
+ =(divf EXP1 ...)=: Return =EXP1 div EXP2 div ...=
+ =(float INT)=: Convert =INT= to a floating point number.
  + Returns the argument itself if it is already a floating-point number.
+ =(floor FLOAT)=, =(ceil FLOAT)=, =(round FLOAT)=, =(trunc FLOAT)=:
  + =floor= returns the first integer that's smaller than or equal to its arugment.
  + =ceil= returns the first integer that's bigger than or equal to its argument.
  + =round= rounds its argument to the nearest integer.
  + =trunc= directly removes the decimal part.
  + Returns the argument itself if it is already an integer.
+ =(leqf EXP1 EXP2)=, =(ltf EXP1 EXP2)=, =(geqf EXP1 EXP2)=, =(gtf EXP1 EXP2)=: Check if =EXP1= is smaller or equal than, strictly smaller than, greater or equal than, and strictly greater than =EXP2= respectively.

+ =(eqnum EXP1 EXP2)=: Return if =EXP1= and =EXP2= has the same numerical value.
  
** Pair

+ =(cons EXP1 EXP2)=: Return the pair of =EXP1= and =EXP2=
+ =(car EXP1)=: Return the first component of the pair =EXP1=.
+ =(cdr EXP1)=: Return the second component of the pair =EXP2=.
+ =(set-car! EXP NEWCAR)=: Set the first component of =EXP= to =NEWCAR=.
+ =(set-cdr! EXP NEWCDR)=: Set the second component of =EXP= to =NEWCAR=.
+ =(w/car EXP NEWCAR)=: Equivalent to =(cons NEWCAR (cdr EXP))=.
+ =(w/cdr EXP NEWCDR)=: Equivalent to =(cons (car EXP) NEWCDR)=.
  
** Character

+ =(chr INT)=: Convert =INT= into the corresponding character.
+ =(ord CHAR)=: Convert =CHAR= into the corresponding integer.
+ =(char? EXP)=: Check if =EXP= is a character.

** String

+ =(strref STR I)=: Retrieve the =I=-th (starting from 0) character of the string =STR=.
+ =(substr STR START END?)=: Retrieve the substring of the string =STR= starting from index =START= to index =END=. =END= is optional; if it's not provided, this function takes the substring starting from index =START= to the end of the string.
+ =(strappend STR1 ...)=: Return the string appended together from its arguments.
+ =(strsym STR)=: Convert a string to a symbol.
+ =(str? EXP)=: Check if =EXP= is a string.

** Boolean

+ =(and EXP1 ...)=:
+ =(or EXP1 ...)=:
+ =(not EXP)=:

** Symbol

+ =(symstr SYM)=: Convert a symbol to a string.
+ =(sym? EXP)=: Check if =EXP= is a symbol.

** List

+ =(list EXP1 ...)=: Combine its arguments into a list.
+ =(nil? EXP)=: Check if =EXP= is an empty list.

** Vector

+ =(vec? EXP)=: Check if =EXP= is a vector.
+ =(vector EXP1 ...)=: Combine its arguments into a vector.
+ =(listvec LIST)=: Convert =LIST= into a vector.
+ =(veclist VEC)=: Conver =VEC= into a list
+ =(vecref VEC INT)=: Return the =INT=-th element from =VEC=.
+ =(mkvec INT)=: Create a vector of size =INT=.
+ =(vecset! VEC INT VALUE)=: Set the =INT=-th element of =VEC= to value =VALUE=.
+ =(vec++ EXP1 ...)=:
+ =(veclen VECTOR)=:
  
** File input/output

+ =stdin=, =stdout=, =stderr=: Standard input, standard output and standard error.
+ =(eof? EXP)=: Check if =EXP= is the EOF object.
+ =(openinput STR)=: Open file =STR= as input.
+ =(openoutput STR MODE?)=: Open file =STR= as output.
  + When =MODE= is not used (i.e. the form is =(openoutput STR)=), the file is opened for writing.
  + When =MODE= is ="a"=, the file is opened for appending.
+ =(close FILE)=: Close a file.
+ =(readch FILE)=: Read a character from an input file.
+ =(writech FILE)=: Write a character to an output file.
  
** Iteration

Iteration is important (at least for now) since we don't have tail-call optimization.

+ =(while COND BODY)=: Repeatedly execute =BODY= until =COND= evaluates to false. Returns nil.

* Extended primitives

A few functions that should be able to be defined using the language itself is defined as primitives for performance, even if there aren't much performance to begin with...

** List libraries

+ =(length LIST)=: Return the length of =LIST=.
+ =(append EXP ...)= / =(list++ EXP ...)=: Combines =EXP= and the rest into one list.
+ =(reverse LIST)=: Return a reversed version of =LIST=.
+ =map=:
+ =filter=:
+ =member=:
+ =assoc=:

** COMMENT Bitwise operations

+ =(bit~ INT)=: Bitwise not.
+ =(bit& INT INT)=: Bitwise and.
+ =(bit^ INT INT)=: Bitwise xor.
+ =(bit| INT INT)=: Bitwise or.
+ =(bit<< INT INT)=: Left shift.
+ =(bit>> INT INT)=: Right shift.
+ =(biti>> INT INT)=: Algorithmic right shift.

** COMMENT Vector operations


** COMMENT String operations

+ =(mkstr N CHAR)=:
+ =(strlen STR)=:
+ =(strlist STR)=: Convert a string to a list of characters.
+ =(strvec STR)=: Convert a string to a vector of characters.
+ =(str++ STR1 ...)=: Equivalent to =strappend=.

** COMMENT Generators

A generator is simply a function that takes no argument and returns a value when called. There are two types of generators: finite and infinite. Generators should return the EOF object when ending.

+ =(generator EXP1 ...)=:
+ =(circular-generator EXP1 ...)=:
+ =(mk-iota-generator )=
+ =(mk-range-generator )=
+ =(gfrom/list LIST)=:
+ =(gfrom/vec LIST)=:
+ =(gfrom/str LIST)=:
+ =(gfrom/reverse-vec LIST)=:
+ =(gcons )=
+ =(gappend )=
+ =(gfilter )=
  

